name: build

on:
  push:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install git-crypt
      run: sudo apt-get install git-crypt

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v ${GITHUB_WORKSPACE}/cmd/tf-init-booster

    - name: Test
      run: go test -v ./...
