name: build

on:
  push:
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code 
      uses: actions/checkout@v2

    - name: Install git-crypt
      run: sudo apt-get install git-crypt

    - name: Build
      run: go build -v .

    - name: Test
      run: GIT_CRYPT_KEY=test-git-crypt-key go test -v .
